include:
  - remote: https://ci-templates.k8s.ilt-dmz.iosb.fraunhofer.de/templates/gitlab-ci-common.yml
  - remote: https://ci-templates.docker01.ilt-dmz.iosb.fraunhofer.de/templates/default/gitlab-ci-k8s-deploy-staging.yml
  - remote: https://ci-templates.docker01.ilt-dmz.iosb.fraunhofer.de/templates/default/gitlab-ci-k8s-deploy-prod.yml

variables:
  DOCKER_HOST: tcp://localhost:2375
  K8S_NAMESPACE: symp
  K8S_KUSTOMIZE_PATH: templates/k8s/overlays/rancher

image: docker

services:
  - docker:18.09-dind

default:
  tags:
    - ILT

ftp-master:
  variables:
    DOCKER_FILE_PATH: ./ftp/
    DOCKER_IMAGE_SUBPROJECT: /ftp
  extends:
    - .docker-build-master

ftp-branch:
  variables:
    DOCKER_FILE_PATH: ./ftp/
    DOCKER_IMAGE_SUBPROJECT: /ftp
  extends:
    - .docker-build-branch

mysql-master:
  variables:
    DOCKER_FILE_PATH: ./mysql/
    DOCKER_IMAGE_SUBPROJECT: /mysql
  extends:
    - .docker-build-master

mysql-branch:
  variables:
    DOCKER_FILE_PATH: ./mysql/
    DOCKER_IMAGE_SUBPROJECT: /mysql
  extends:
    - .docker-build-branch

camunda:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull camunda/camunda-bpm-platform
    - docker tag camunda/camunda-bpm-platform gitlab-ext.iosb.fraunhofer.de:4567/symp/symp-docker/camunda
    - docker push gitlab-ext.iosb.fraunhofer.de:4567/symp/symp-docker/camunda

filezilla-web-client:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull jlesage/filezilla
    - docker tag jlesage/filezilla gitlab-ext.iosb.fraunhofer.de:4567/symp/symp-docker/filezilla-client
    - docker push gitlab-ext.iosb.fraunhofer.de:4567/symp/symp-docker/filezilla-client

test:
  stage: test
  image:
    name: bitnami/kubectl
  script:
    - kubectl