include:
  - remote: https://ci-templates.k8s.ilt-dmz.iosb.fraunhofer.de/templates/gitlab-ci-common.yml

variables:
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:18.09-dind

default:
  tags:
    - ILT

ftp-master:
  variables:
    DOCKER_FILE_PATH: ./ftp/
    DOCKER_IMAGE_SUBPROJECT: /ftp
  extends:
    - .docker-build-master

ftp-branch:
  variables:
    DOCKER_FILE_PATH: ./ftp/
    DOCKER_IMAGE_SUBPROJECT: /ftp
  extends:
    - .docker-build-branch

docker_hello_world:
 image: hello-world
 services:
   - docker:dind
 before_script:
    - docker login -u "#CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
 script:
  - docker build --pull -t "$CI_REGISTRY_NAMEE" .
  - docker pus "$CI_REGISTRY_IMAGE"
