version: '3.3'
services:
    ftp:
        build: ./ftp
        ports:
            - "20-22:20-22"
            - "21100-21110:21100-21110"
        container_name: ftp
        environment:
            PUBLICHOST: "localhost"
            FTP_USER: admin
            FTP_PASS: admin
        restart: always
        
    camunda:
        build: ./camunda
        container_name: camunda
        restart: always
        ports:
            - '8080:8080'
            
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 0b53c4f
            MYSQL_DATABASE: security_analysis_repository
        ports:
            - '3306:3306'
        volumes:
            - './mysql/config/conf.d/conf.cnf:/etc/mysql/conf.d/conf.cnf'
  
    filezilla:
        container_name: filezilla
        ports:
            - '5800:5800'
        volumes:
            - '/docker/appdata/filezilla:/config:rw'
            - '$HOME:/storage:rw'
        image: jlesage/filezilla
