version: '3.3'
services:
    ftp:
        build: ./ftp
        ports:
            - 20-21:20-21
            - 21100-21110:21100-21110
            - 990:990
        container_name: ftp
        environment:
            FTP_USER: admin
            FTP_PASS: admin
        restart: always
        networks:
            service1_net:
        
    camunda-bpm-platform:
        build: ./camunda
        container_name: camunda
        restart: always
        ports:
            - '8080:8080'
        networks:
            service1_net:
            
    mysql:
        build: ./mysql   
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 0b53c4f
            MYSQL_DATABASE: security_analysis_repository
        ports:
            - '3306:3306'
        networks:
            service1_net:

    camunda-master:
        variables:
            DOCKER_FILE_PATH: ./camunda/
            DOCKER_IMAGE_SUBPROJECT: /camunda
        extends:
            - .docker-build-master

    camunda-branch:
        variables:
            DOCKER_FILE_PATH: ./camunda/
            DOCKER_IMAGE_SUBPROJECT: /camunda
        extends:
            - .docker-build-branch
                                  
networks:
  service1_net:
     
