version: '3.3'
services:
    ftp:
        build: ./ftp
        ports:
            - 20-21:20-21
            - 21100-21110:21100-21110
            - 990:990
        container_name: ftp
        environment:
            FTP_USER: admin
            FTP_PASS: admin
        restart: always
        networks:
            service1_net:
        
    camunda-bpm-platform:
        build: ./camunda
        container_name: camunda
        restart: always
        ports:
            - '8080:8080'
        networks:
            service1_net:
            
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 0b53c4f
            MYSQL_DATABASE: security_analysis_repository
        ports:
            - '3306:3306'
        networks:
            service1_net:
        volumes:
            - './mysql/config/conf.d/conf.cnf:/etc/mysql/conf.d/conf.cnf'
                                  
networks:
  service1_net:
     
