version: '3.3'
services:
    ftp:
        image: metabrainz/docker-anon-ftp
        volumes:
            - './ftp_dir:/var/ftp:ro'
        ports:
            - '20:20'
            - '21:21'
            - '65500-65515:65500-65515'            
        container_name: ftp
        restart: always
        networks:
            service1_net:
                ipv4_address: 172.22.0.101
        
    camunda-bpm-platform:
        image: 'camunda/camunda-bpm-platform:latest'
        container_name: camunda
        restart: always
        ports:
            - '8080:8080'
        volumes:
            # Mounting the whole folder will create a clean distro without webapps and examples
            # Thats why custom apps must be added separately
            #Example: 
            #- './camunda_webapps/*your_custom_app.war*:/camunda/webapps/*your_custom_app.war*'
            - './camunda_webapps/reasoningbpm-1.0.0.war:/camunda/webapps/reasoningbpm-1.0.0.war'
            
    mysql:
        image: mysql   
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 0b53c4f
            MYSQL_DATABASE: security_analysis_repository
        volumes:
            - './mysql_config:/etc/mysql/conf.d'
        networks:
            service1_net:
                ipv4_address: 172.22.0.100
            
            
networks:
  service1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16  
           
     
