version: '3.3'
services:
    ftp:
        build: ./ftp
        ports:
            - 20-21:20-21
            - 21100-21110:21100-21110
        container_name: ftp
        environment:
            FTP_USER: admin
            FTP_PASS: admin
        restart: always
        networks:
            service1_net:
        
    camunda-bpm-platform:
        build: ./camunda
        container_name: camunda
        restart: always
        ports:
            - '8080:8080'
        volumes:
            # Mounting the whole folder will create a clean distro without webapps and examples
            # Thats why custom apps must be added separately
            #Example: 
            #- './camunda_webapps/*your_custom_app.war*:/camunda/webapps/*your_custom_app.war*'
            - './camunda_webapps/reasoningbpm-1.0.0.war:/camunda/webapps/reasoningbpm-1.0.0.war'
            
    mysql:
        build: ./mysql   
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 0b53c4f
            MYSQL_DATABASE: security_analysis_repository
        ports:
            - '3306:3306'
        networks:
            service1_net:
    
    test:
        stage: test
        script: mvn --version
                  
networks:
  service1_net:
     
