version: '3.5'
services:
    symp-ftp:
        build: ./ftp
        ports:
            - "20-21:20-21"
            - "21100-21110:21100-21110"
        container_name: symp-ftp
        environment:
            PUBLICHOST: "localhost"
            FTP_USER: admin
            FTP_PASS: admin
        restart: unless-stopped
        networks:
            - symp
        
    symp-camunda:
        build: ./camunda
        container_name: symp-camunda
        restart: unless-stopped
        ports:
            - '8080:8080'
        networks:
            - symp
            
    symp-mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: symp-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 0b53c4f
            MYSQL_DATABASE: security_analysis_repository
        ports:
            - '3306:3306'
        volumes:
            - './mysql/config/conf.d/conf.cnf:/etc/mysql/conf.d/conf.cnf'
        networks:
            - symp
  
    symp-filezilla:
        container_name: symp-filezilla
        ports:
            - '5800:5800'
        volumes:
            - '/docker/appdata/filezilla:/config:rw'
            - '$HOME:/storage:rw'
        image: jlesage/filezilla
        restart: unless-stopped
        networks:
            - symp
            
networks:
    symp:
        external:
            name: symp
